[build]
beforeDevCommand = "pnpm dev"
beforeBuildCommand = "pnpm build"
devPath = "http://localhost:1420"
distDir = "../dist"
withGlobalTauri = false

[package]
productName = "matcha"
version = "0.0.1"

[tauri]
macOSPrivateApi = true
[[tauri.windows]]
title = "Matcha"
fullscreen = false
height = 800
width = 1280
minHeight = 640
minWidth = 798
resizable = true
center = true
decorations = false
transparent = true

[tauri.allowlist]
app.all = true
os.all = true
path.all = true
fs.all = true
fs.scope = ["$APPCACHE/*","$APPCACHE/*/**"]

[tauri.allowlist.shell]
all = false
open = true

[tauri.allowlist.window]
all = true

[tauri.bundle]
active = true
category = "DeveloperTool"
copyright = ""
externalBin = []
icon = [
    "icons/32x32.png",
    "icons/128x128.png",
    "icons/128x128@2x.png",
    "icons/icon.icns",
    "icons/icon.ico",
]
identifier = "com.akirami.matcha"
longDescription = ""
resources = []
shortDescription = ""
targets = "all"

[tauri.bundle.deb]
depends = []

[tauri.bundle.macOS]
exceptionDomain = ""
frameworks = []

[tauri.bundle.windows]
digestAlgorithm = "sha256"
timestampUrl = ""
wix.language = "zh-CN"

[tauri.security]

[tauri.updater]
active = false
