template: $CHANGES
category-template: "### $TITLE"
change-template: "- $TITLE ([#$NUMBER]($URL)) @$AUTHOR"
change-title-escapes: '\<&'
exclude-labels:
  - "dependencies"
  - "skip changelog"
categories:
  - title: "ðŸ’¥ é‡å¤§å˜æ›´"
    labels:
      - "breaking"
  - title: "âœ¨ æ–°åŠŸèƒ½"
    labels:
      - "enhancement"
  - title: "ðŸ› é”™è¯¯ä¿®å¤"
    labels:
      - "bug"
  - title: "ðŸŽ¨ UI/UX"
    labels:
      - "UI/UX"
  - title: "ðŸ’« æ‚é¡¹"
