/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    AList: typeof import('ant-design-vue/es')['List']
    AListItem: typeof import('ant-design-vue/es')['ListItem']
    AListItemMeta: typeof import('ant-design-vue/es')['ListItemMeta']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ARadioButton: typeof import('ant-design-vue/es')['RadioButton']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASkeleton: typeof import('ant-design-vue/es')['Skeleton']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    Avatar: typeof import('./src/components/Avatar.vue')['default']
    ChatAction: typeof import('./src/components/ChatAction.vue')['default']
    ChatBox: typeof import('./src/components/ChatBox.vue')['default']
    ChatBoxTopbar: typeof import('./src/components/ChatBoxTopbar.vue')['default']
    ChatContact: typeof import('./src/components/ChatContact.vue')['default']
    ChatContactItem: typeof import('./src/components/ChatContactItem.vue')['default']
    ChatInput: typeof import('./src/components/ChatInput.vue')['default']
    ChatMessage: typeof import('./src/components/ChatMessage.vue')['default']
    ContextMenu: typeof import('./src/components/ContextMenu.vue')['default']
    CreateGroupForm: typeof import('./src/components/CreateGroupForm.vue')['default']
    CreateMemberForm: typeof import('./src/components/CreateMemberForm.vue')['default']
    CreateUserForm: typeof import('./src/components/CreateUserForm.vue')['default']
    HighlightCode: typeof import('./src/components/HighlightCode.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    MessageContent: typeof import('./src/components/MessageContent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBox: typeof import('./src/components/SearchBox.vue')['default']
    SelectUserList: typeof import('./src/components/SelectUserList.vue')['default']
    SendButton: typeof import('./src/components/SendButton.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    ThemeSwitch: typeof import('./src/components/ThemeSwitch.vue')['default']
    TimeSeparator: typeof import('./src/components/TimeSeparator.vue')['default']
    Titlebar: typeof import('./src/components/Titlebar.vue')['default']
    WaveAudioPlayer: typeof import('./src/components/WaveAudioPlayer.vue')['default']
  }
}
